#!/bin/bash
set -euo pipefail

# adb-ip
#   Reconnects the current (usb connected) android device over ip (port 5555)

ip=$(adb -d shell ifconfig | grep -oP '(?<=addr:)192\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
adb -d tcpip 5555
adb connect "$ip:5555"