#!/bin/bash

# Get work items by numbers provided on stdin
# Requires:
#  * js
#  * A file called .azure that include varible definiton for:
#      * $ORG  - The Azure devops organization to use
#      * $PROJ - The Azure devops project to use
#      * $PAT  - An Azure Personal Access Token that can read work items

source .azure

url="https://dev.azure.com/$ORG/$PROJ/_apis/wit/workitemsbatch?api-version=6.1-preview.1"

sed -E 's/^#//' | jq -cs '{"$expand":"None","fields":["System.Title","System.WorkItemType"],"ids":.}' | \
    curl "$url" -H "Content-Type: application/json" -u ":$PAT" -d @- | \
    jq -r '.value[] | [.id , .fields["System.WorkItemType"] , .fields["System.Title"]] | @tsv'