#!/bin/bash
set -euo pipefail

# git add-ws
#   Stages all whitespace pending changes, removing anything already staged

cd $(git rev-parse --show-toplevel)
git add -u && git diff --cached -w --no-prefix | git apply --cached -R -p0