#!/bin/bash

# git tweb <action> [<branch>]
# Open the tfs git webpage for the given action and given branch, valid actions are:
#
# pull-requests (prs)
# : Lists all pull requests
#
# pull-request (pr)
# : Shows the pull request for the current branch to dev
#
# branch
# : Shows the given branch
#
# work-items (wis)
# : Shows work items releated to the current project
#
# user-story, work-item (us, wi)
# : Checks the branch name for a work item id, and opens it
#
# build, builds
# : Shows the builds for the project
#
# release, releases
# : Shows the releases for the project


# azure ssh remotes are of the form:
#   git@ssh.<azure-url>:<version>/<company>/<project>/<repo>
readarray -td"/" repoParts <<< "$(git remote get-url origin | tr -d '\n')"
company="${repoParts[1]//[$'\t\r\n']}"
project="${repoParts[2]//[$'\t\r\n']}"
gitRepo="${repoParts[3]//[$'\t\r\n']}"

action=$1
shift

function aorb(){
    if [[ -z "$1" ]]; then
        echo "$2"
    else
        echo "$1"
    fi
}

function goto(){
    start "https://dev.azure.com/$company/$project/_$1"
}

function gotoRepo(){
    start "https://dev.azure.com/$company/$project/_git/${gitRepo}/${2}"
}

case $action in
    #Broken
    prs|pull-requests)
        gotoRepo "pullrequests"
        ;;
    pr|pull-request)
        to=$(aorb $1 dev)
        point=$(aorb $2 HEAD)
        branch=$(git rev-parse --abbrev-ref $point | sed -e 's/\//%2F/g')
        #start "${repo}/pullrequests?sourceRef=${branch}&targetRef=${to}&_a=createnew"
        #start "${repo}/pullrequestcreate?sourceRef=${branch}&targetRef=${to}"
        gotoRepo "pullrequestcreate?sourceRef=${branch}&targetRef=${to}"
        ;;
    branch)
        point=$(aorb $1 HEAD)
        branch=$(git rev-parse --abbrev-ref $point | sed -e 's/\//%2F/g')
        gotoRepo "?version=GB${branch}&_a=history"
        ;;
    wis|work-items)
        goto "workitems"
        ;;
    us|wi|user-story|work-item)
        point=$(aorb $1 HEAD)
        workItemId=$(git rev-parse --abbrev-ref $point | egrep -o '[0-9]+' | head -1)
        start "https://dev.azure.com/$company/${project}/_workitems?id=${workItemId}&_a=edit"
        ;;
    build|builds)
        goto "_build"
        ;;
    release|releases)
        goto "_release"
        ;;
    ""|repo)
        gotoRepo
        ;;
    #Broken
    list|list-all|all)
        point=$(aorb $1 HEAD)
        branch=$(git rev-parse --abbrev-ref $point | sed -e 's/\//%2F/g')
        workItemId=$(git rev-parse --abbrev-ref $point | egrep -o '[0-9]+' | head -1)

        repoBase="https://dev.azure.com/$company/$project/_git/${gitRepo}"
        projectBase="https://dev.azure.com/$company/$project/"

        echo "   Repository: ${repoBase}"
        echo "Pull requests: ${repoBase}/pullrequests"
        echo "   Work items: ${projectBase}/_workitems"
        echo "       Branch: ${repoBase}/?version=GB${branch}&_a=history"
        [ -n "$workItemId" ] && echo "    Work item: ${projectBase}/_workitems/edit/${workItemId}"
        ;;
    *)
        echo "Unknown action $action"
        ;;
esac