#!/bin/bash
set -euo pipefail

# git lr <left> <right>
#
# Prints a side by side listing of commits on each branch
# Warning: breaks quite hard with emoji

# TODO: fix for emoji

cols=$(tput cols)
size=$(($cols/ 2))
tput bold
printf "%-${size}s %-${size}s\n" " Only on $1" "Only on $2"
tput sgr0

pr -m -t -w $cols <(\
    git log --color=always --no-merges --pretty=graph --date=relative "$2..$1" \
) <(\
    git log --color=always --no-merges --pretty=graph --date=relative "$1..$2" \
)