#!/bin/bash

#Replaces existing hooks with template hooks

cd $(git rev-parse --show-toplevel)
templateHooksDir="$(git config --path --get init.templatedir)"/hooks
currentHooksDir="$(git rev-parse --git-dir)"/hooks

for s in "$templateHooksDir"/*; do
    [ -x "$s" ] || continue;
    file="$(basename $s)"
    [ -f "$currentHooksDir/$file" ] || continue;
    echo "Updating $file"
    rm "$currentHooksDir/$file"
done

git init