#!/bin/bash
#Start Release branch

#git start-release [version] [folders...]

version=$1
shift

echo "Starting release 'release/$version' on:"
for f; do (
    echo
    echo "  $f"
    cd "$f";
    git fetch origin dev 2>&1 | sed 's/^/    /g';
    git branch "release/$version" FETCH_HEAD
    git push -u --no-verify origin "release/$version":"refs/heads/release/$version" 2>&1 | sed 's/^/    /g';
); done