#!/bin/bash
set -euo pipefail

# git onwithit
#   Updates all files, continues the current operation, then display the status

# Requires: git-action

case $(git action) in
    rebase*) action=rebase ;;
    cherry-pick) action=cherry-pick ;;
    revert) action=revert ;;
    am) action=am ;;
    merge) action=merge ;;
    *)
        echo "Not inside a rebase, cherry-pick, revert, or am"
        exit 1 ;;
esac

git diff --check \
  && git add -u \
  && git $action --continue \
  || echo "Warning: Issue occoured when checking, adding or continuing. Check all conflcits are resolved"

git status