#!/bin/bash

# Lists all git aliases & git helper commands

echo "Alises:"
git config --get-regexp ^alias\. | sed 's/^alias\.//; s/\s\+/ /g; s/^/  /'

echo "Scripts"
find ~/bin -name 'git-*' | sed 's#.*/git-#  git #'