#!/bin/bash

# git-clean-done <merged-into>: Remove merged branches both locally and remotely

if [ -z "$1" ]; then
    target="HEAD"
else
    target="$1"
fi

git for-each-ref --merged "$target" --no-contains "$target" refs/heads/ --shell --format \
    "git branch -D %(refname:short);" | sh