#!/bin/bash
set -euo pipefail

# git-qcommit <target branch> [<git commit options...>]
#   Commits the work to a new branch, pushes it, then swaps back
#   Designed for single action bug fixes when policies inforce pull requests

branch=$1
shift

oldHead=$(git symbolic-ref --short HEAD)
git branch $branch
git checkout $branch --

git commit "$@" && \
git push -u origin "$branch:$branch"
git checkout $oldHead --