#!/bin/bash
set -euo pipefail

# git eosmc (end of sprint merge check)
#
# Checks for diffrences that exist on master but not dev, and starts a pull
# request if any are found

# Requies: git-tweb

git diff "dev...${1:-master}" --exit-code || git tweb pr dev "${1:-master}"