#!/bin/bash
set -euo pipefail

# git evergreen
#   Shows the history of the master, dev, and current release branch, going
#   back to their common ancestor

release="$(git for-each-ref --format='%(refname)' refs/heads/release --sort=-refname --count 1)"
base="$(git merge-base --octopus "$release" master dev)"

git tree "$release" master dev "^$base" "$@"