#!/bin/bash
set -euo pipefail

# git apples
#   Shows a tree log of all the steashed commits in the project

export LESSOPEN="|-sed '/^ /a\ ' %s"
git reflog refs/stash --format=%H^^..%H | \
git log --color --stdin  --pretty=graph --date=relative --graph "$@"