#!/bin/bash

#Replaces existing hooks with template hooks

cd $(git rev-parse --show-toplevel)
templateHooksDir="$(git config --path --get init.templatedir)/hooks"
currentHooksDir="$(git rev-parse --git-dir)/hooks"

cp -Lrv C:/Users/stuart.watson/.git_template/hooks/* .git/hooks
