#!/bin/bash
set -euo pipefail

#If packages or node_modules: stop (prune)
#Otherwise: If bin or obj: execute ynrfmf and stop (prune)
find -type d \( -name packages -o -name node_modules \) -prune -o \( -name bin -o -name obj \) -prune -exec ynrmf {} +
